-- COMANDOS SQL - DIVISÃO: DQL / DRS
-- DQL (Data Query Language) -> LINGUAGEM DE CONSULTA DE DADOS
-- DRS (Data Retrieve Language ) -> LINGUAGEM DE RECUPERAÇÃO DE DADOS 

-- ALGUNS AUTORES TRATAM COMO DML - Data Manipulation Language)
-- COMANDO: SELECT -> COMANDO PARA CONSULTA/RECUPERAÇÃO DE DADOS
-- NESTE MATERIAL IREMOS TRATAR DE CONSULTA SIMPLES (CONSULTA A APENAS UMA TABELA)

-- CONSULTANDO TODAS AS LINHAS E COLUNAS DA TABELA FUNCIONARIO
SELECT * FROM T_SIP_FUNCIONARIO;
-- SELECT -> CONSULTA
-- * -> REPRESENTA TODAS AS COLUNAS DA TABELA
-- FROM -> CLAUSULA QUE INDICA AS TABELAS A SEREM CONSULTADAS
-- T_SIP_FUNCIONARIO -> NOME DA TABELA A SER CONSULTADA
-- PODEMOS ACRESCENTAR A CONDIÇÃO DA CONSULTA, ATRAVÉS DA CLAUSULA WHERE
-- DESTA FORMA, FILTRAMOS AS LINHAS QUE DEVEM SER CONSULTADAS
-- QUANDO TEMOS UMA CONSULTA COM A CLAUSULA WHERE, GARANTIMOS QUE NÃO
-- ESTAMOS CONSULTANDO A TABELA INTEIRA


-- Especificando as colunas que deseja consultar e filtrando as linhas da tabela FUNCIONARIO.  
SELECT CD_DEPTO, NR_MATRICULA, NM_FUNCIONARIO, VL_SAL_MEN
    FROM T_SIP_FUNCIONARIO
    WHERE CD_DEPTO = 3;

-- TEMOS UMA CONSULTA, ONDE RECUPERAMOS TODOS OS FUNCIONARIOS QUE 
-- TRABALHAM NO DEPTO DE CODIGO IGUAL A 3
-- EXIBIMOS: CODIGO DEPTO, NOME, MATRICULA E O SALARIO DO FUNCIONARIO
-- VEJA QUE A CONDIÇÃO FILTRA QUAIS LINHAS DEVEM SER RECUPERADAS

 
/*
Dê preferencia a consultas onde as colunas e filtro são especificados, com isso evitamos
retornar informações que não serão utilizadas pelo usuário.
*/

-- RECUPERANDO OS DEPARTAMENTOS (SEM REPETIÇÃO) QUE POSSUEM FUNCIONARIOS.
-- QUAIS DEPTOS POSSUEM FUNCIONARIOS TRABALHANDO?
-- RESPOSTA: DEPTOS: 1,2,3,4,5
SELECT DISTINCT CD_DEPTO FROM T_SIP_FUNCIONARIO;
--OU
SELECT UNIQUE CD_DEPTO FROM T_SIP_FUNCIONARIO;

-- VISUALIZAR TODOS OS DEPTOS ASSOCIADOS A FUNCIONARIOS
SELECT CD_DEPTO, NM_FUNCIONARIO FROM T_SIP_FUNCIONARIO;

-- QUAIS PROJETOS ESTÃO EM IMPLANTACAO?
-- RESPOSTA: 10001, 10002, 10003,10004,10005
SELECT UNIQUE CD_PROJETO FROM T_SIP_IMPLANTACAO;

-- QUAIS FUNCIONARIOS POSSUEM DEPENDENTES?
-- RESPOSTA: 12347, 12349, 12350
SELECT UNIQUE NR_MATRICULA FROM T_SIP_DEPENDENTE;

-- Exemplo de consulta utilizando operadores aritméticos
-- RECUPERAR OS FUNCIONARIOS, APLICANDO 5% AUMENTO NO SALARIO
SELECT CD_DEPTO, NM_FUNCIONARIO, VL_SAL_MEN, VL_SAL_MEN * 1.05 -- CALCULO AJUSTE DE 5% NO SALARIO
    FROM T_SIP_FUNCIONARIO;

-- UTILIZANDO APELIDOS (ALIAS) DE COLUNAS
SELECT CD_DEPTO, NM_FUNCIONARIO, VL_SAL_MEN AS "SALARIO MENSAL", 
       VL_SAL_MEN * 1.05 AS "SALARIO REAJUSTADO" -- CALCULO AJUSTE DE 5% NO SALARIO
    FROM T_SIP_FUNCIONARIO;
    
-- A OPÇÃO AS É OPCIONAL
-- AS ASPAS DUPLAS, USAMOS QUANDO O APELIDO ENVOLVER PALAVRAS COMPOSTAS E
-- COM CARACTERES ESPECIAIS 

SELECT CD_DEPTO, NM_FUNCIONARIO, VL_SAL_MEN "SALARIO MENSAL", 
       VL_SAL_MEN * 1.05 SALARIO_REAJUSTADO -- CALCULO AJUSTE DE 5% NO SALARIO
  FROM T_SIP_FUNCIONARIO;

-- APRESENTANDO RESULTADOS DE FORMA ORDENADA
-- ORDER BY ASC (ASCENDENTE/CRESCENTE)
-- RECUPERAR TODOS OS DEPTOS EM ORDEM ALFABETICA CRESCENTE (A -> Z)
  SELECT CD_DEPTO, NM_DEPTO
    FROM T_SIP_DEPARTAMENTO
ORDER BY NM_DEPTO ASC; --ASC = CRESCENTE
                       -- OPÇÃO ASC (DEFAULT) CRESCENTE
                       -- CASO NÃO INFORME A OPÇÃO APÓS A COLUNA NO
                       -- ORDER BY, A OPÇÃO DEFAULT E CONSIDERADA
                       
-- RECUPERAR TODOS OS DEPTOS EM ORDEM ALFABETICA CRESCENTE (A <- Z)
  SELECT CD_DEPTO, NM_DEPTO
    FROM T_SIP_DEPARTAMENTO
ORDER BY NM_DEPTO DESC;

-- PODEMOS ORDENAR POR MAIS DE UMA COLUNA
-- RECUPERAR OS FUNCIONARIOS, ORDENADOS POR DEPTO(ASC) E SALARIO(DESC)
  SELECT CD_DEPTO, NR_MATRICULA, NM_FUNCIONARIO, VL_SAL_MEN
    FROM T_SIP_FUNCIONARIO
ORDER BY CD_DEPTO ASC, VL_SAL_MEN DESC;

-- ORDER BY UTILIZANDO NÚMEROS QUE REPRESENTAM A POSIÇÃO DAS COLUNAS
-- NO COMANDO SELECT
  SELECT CD_DEPTO, NR_MATRICULA, NM_FUNCIONARIO, VL_SAL_MEN
    FROM T_SIP_FUNCIONARIO
ORDER BY 1 ASC, 4 DESC;

--ORDENANDO COLUNAS QUE POSSUEM ALIAS
SELECT CD_DEPTO, NM_FUNCIONARIO, VL_SAL_MEN AS "SALARIO MENSAL", 
       VL_SAL_MEN * 1.05 AS "SALARIO REAJUSTADO" -- CALCULO AJUSTE DE 5% NO SALARIO
 FROM T_SIP_FUNCIONARIO
ORDER BY "SALARIO REAJUSTADO" DESC;

-- FILTROS POR NUMEROS, TEXTO E DATA
-- RECUPERANDO TODOS OS FUNCIONARIOS COM SALARIO >= 3000.56
  SELECT NR_MATRICULA, NM_FUNCIONARIO, VL_SAL_MEN
    FROM T_SIP_FUNCIONARIO
   WHERE VL_SAL_MEN >= 3000.56 --USAR O PONTO DECIMAL
ORDER BY VL_SAL_MEN DESC;

--DATA
  SELECT NR_MATRICULA, NM_FUNCIONARIO, DT_ADMISSAO
    FROM T_SIP_FUNCIONARIO
   WHERE DT_ADMISSAO >= TO_DATE ('01/08/2015', 'DD/MM/YYYY')
ORDER BY DT_ADMISSAO ASC;

-- TEXTO
-- RECUPERANDO TEXTO
-- CONTEUDO DO BANCO É CASE SENSITIVE (DIFERENCIAÇÃO ENTRE MAIUSCULAS E
-- MINUSCULAS)
-- UPPER(VALOR) -> CONVERTE UM CONTEUDO PARA LETRAS MAIUSCULAS
-- LOWER(VALOR) -> CONVERTE UM CONTEUDO PARA LETRAS MINUSCULAS

SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE NM_FUNCIONARIO = 'joão da silva';
 
SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE NM_FUNCIONARIO = 'JOÃO DA SILVA';

SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE LOWER(NM_FUNCIONARIO) = 'JOÃO DA SILVA';

SELECT NR_MATRICULA, NM_FUNCIONARIO
  FROM T_SIP_FUNCIONARIO
 WHERE UPPER(NM_FUNCIONARIO) = 'joão da silva';