-- COMANDOS DNL --> LINGUAGEM DE MANIPULAÇÃO DE DADOS
--COMANDOS:  INSERT/UPDATE/DELETE (CRUD)

--COMANDOS NÃO SÃO CASE SENSITIVE
-- CONTEUDO ARMAZENADOS É CASE SENSITIVE

--COMMIT ; EFETIVA (SALVA) AS TRANSAÇÕES DISCO

--POPULAR (INSERÇÃO) A TABELA DEPARTAMENTO

/*
INSERT INTO T_SIP_DEPARTAMENTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
        VALUES(1, 'FINANCEIRO', 'FIN')      ;
      
INSERT INTO T_SIP_DEPARTAMENTO VALUES (2, 'MARKETING', 'MKT');        
*/

--EXEMPLO ENVOLVENDO INSERÇÃO DE DATA/HORA
--INSERT INTO T_SIP_PROJETO VALUES( 1001, 'PROJETO ABC', TO_DATE('10/09/2020','DD/MM/YYYY'), TO_DATE('15/03/2022','DD/MM/YYYY'));   
--EXEMPLO DE ATUALIZAÇÃO DE UMA OU MAIS COLUNAS DA TABELA, AFETANDO UMA OU MAIS LINHAS

--IMPORTANTE         ORACLE (MM/DD/YYYY)
--TO DATE('10/09/2020', 'DD/MM/YYYY)  09/10/2020
-- (15/03/2022)     15/03/2022     NÃO EXISTE MES 15

--EXEMPLO DE INSERÇÃO DE VALORES DECIMAIS E CHAVE ESTRANGEIRA(RELACIOMENTO)
/*
INSERT INTO T_SIP_FUNCIONARIO
     VALUES (12345, 1 ,'JOÃO DA SILVA', TO_DATE('10/08/1985','DD/MM/YYYY'), TO_DATE('22/03/2020', 'DD/MM/YYYY'),'RUA X,25', 3853.67);
*/
--VALORES DECIMAIS DEVEM USAR PONTO DECIMAL
--CHAVE ESTRANGEIRA (CD_DEPTO), DEVE SER INFORMADO UM VALOR
--CADASTRO NA TABELA DEPTO, CASO CONTRARIO NÃO ENCONTRA A REFERENCIA E ACARRETARÁ EM ERRO

--EXEMPLO DE INSERÇÃO DE VALORES NULOS EM CAPOS OPCIONAIS
--IMPLICITA IREMOS OMITIR A COLUNA OPCIONAL NA DECLARAÇÃO DO COMANDO A COLUNA OPCIONAL E A DA TERMINO

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO)
    VALUES(1002,'PROJETO DEF', TO_DATE('15/08/2019','DD/MM/YYYY'));
    --COLUNA DT_TERMINO QUE NÃO FOI INFORMADA SERÁ PREENCHIDA COM NULL
    
--EXPLICITA DECLARA A COLUNA NA LINHA DE COMANDO
INSERT INTO T_SIP_PROJETO VALUES(1003, 'PROEJTO GHI', TO_DATE('25/10/2021', 'DD/MM/YYYY'), NULL);
/*
UPDATE T_SIP_DEPARTAMENTO
   SET NM_DEPTO = 'TESTE',
       SG_DEPTO = 'TST'
WHERE CD_DEPTO = 1;
*/
--WHERE INFORMA A CONDIÇÃO PARA A ATUALIZAÇÃO
--ONDE SOMENTE AS LINHAS QUE ATENDEM A ESSA CONDIÇÃO SERÃO ALTERADAS
--UPDATE SEM WHERE MODIFICA TODAS AS LINHAS DA TABELA

--EXEMPLO DE UPDATE ALTERANDO DATA/HORA
--ALTERA O NOME E A DATA DE NASCIMENTO DE UM FUNCIONARIO
UPDATE T_SIP_FUNCIONARIO
   SET NM_FUNCIONARIO = 'JOÃO DA SILVA XAVIER',
       DT_NASCIMENTO = TO_DATE('10/08/1997', 'DD/MM/YYYY')
 WHERE NR_MATRICULA = 12345;
 
 --UMA SITUAÇÃO DE UPDATE SEM WHERE
 --ATUALIZAR O SALARIO DE TODOS OS FUNCIONARIOS DA EMPRESA SERÁ CONCEDIDO UM AUMENTO DE 5% PARA TODOS OS FUNCIONARIOS
UPDATE T_SIP_FUNCIONARIO
   SET VL_SAL_MEN = VL_SAL_MEN * 1.05;
    
COMMIT ;


--EXEMPLO DE CONSULTA A TABELA
SELECT * FROM T_SIP_DEPARTAMENTO;
SELECT * FROM T_SIP_PROJETO;
SELECT * FROM T_SIP_FUNCIONARIO;
--CONSULTE TODAS AS COLUNAS/CAMPOS E LINHAS DA TABELA DEPTO
-- * => TODAS AS COLUNAS
--CONSULTA SEM CONDIÇÃO => RECUPERAR TODAS AS LINHAS DA TABELA

--EXEMPLO DE COMANDO DE DELEÇÃO
--DELETE ELIMINA/APAGA UMA OU MAIS LINHAS DA TABELA
--DEVEMOS INSERIR A CONDIÇÃO 'WHERE' PARA INDICAR QUAIS LINHAS DEVEM SER APAGADAS
/*
DELETE FROM T_SIP_DEPARTAMENTO
WHERE cd_depto=1;
*/
--SEMPRE INFORMAR A CONDIÇÃO NO MOMENTO DA DELEÇÃO
--DELETE SEM WHERE TODAS AS LINHAS DA TAVELA SERÃO ELIMINADAS

--REALIZANDO COPIA DE DADOS DE UMA TABELA PARA OUTRA CRIAR UMA TABELA PARA REALIZAR A CÓPIA

/*
CREATE TABLE T_SIP_COPY_PROJETO_FIN(
    CD_PROJETO      NUMBER(5)       NOT NULL,
    NM_PROJETO      VARCHAR2(40)    NOT NULL,
    DT_INICIO       DATE            NOT NULL,
    DT_TERMINO      DATE            NOT NULL
);

--CHAVE PRIMARIA DA TABELA COPIA PROJETOS FINALIZADOS
   ALTER TABLE      T_SIP_COPY_PROJETO_FIN
ADD CONSTRAINT      PK_SIP_COPY_PROJETO_FIN
   PRIMARY KEY      (CD_PROJETO);
 */  
--REALIZANDO A COPIA DOS DADOS DE UMA TABELA PARA OUTRA UTILIZANDO O COMANDO INSERT E O COMANDO SELECT (SUBCONSULTA OU SUBQUERY)
INSERT INTO T_SIP_COPY_PROJETO_FIN(SELECT * FROM T_SIP_PROJETO WHERE DT_FIM_PROJETO IS NOT NULL);
SELECT * FROM T_SIP_COPY_PROJETO_FIN;

--OS PROJETOS FINALIZADOS, POSSUEM A DATA TERMINO INFORMADA PORTANTO A VALIDAÇÃO,
--PERGUNTAMOS SE A DATA TERMINO NÃO É NULA(POSSUI DATA/IS NOT NULL)
--PARA FAZER ESTA VALIDAÇÃO UTILIZAMOS O OPERADOR IS NOT NULL
--NÃO FUNCIONA SE ESCREVERMOS DT_TERMINO <> NULL(POIS NULL NÃO TEM VALOR, E NÃO PODEMOS USAR OPERADOR RELACIONAL)

--DESTA FORMA NÃO FUNCIONA, PORQUE NUO NÃO TEM VALOR
--DT_TERMINO == NULL
--DT_TERMINO <> NULL

--FUNCIONA APENAS DESTA FORMA