-- EXEMPLOS JOIN
-- MATERIAL DE APOIO:
-- Aula17_TDS_DMSQL_DRS_JUNCAO_TABELAS_RitaCRodrigues.PDF 

-- JUNÇÕES POR IGUALDADE, ONDE TEMOS RELACIONAMENTOS E COMPARAÇÃO DE CHAVE PRIMARIA = CHAVE ESTRANGEIRA

-- INNER JOIN = JUNÇÃO INTERNA = INTERSECÇÃO ENTRE CONJUNTOS = RECUPERAR TUDO QUE SE ASSOCIA

-- EXEMPLO - EQUIJOIN (IGUALDADE)
-- SINTAXE: SQL/99 (VERSÃO PADRONIZOU OS JOIN´s)
-- RECUPERAR TODOS OS FUNCIONARIOS QUE TRABALHAM EM DEPTOS (FUNCIONARIOS ASSOCIADOS A DEPTOS)
-- (QUAIS FUNCIONARIOS E QUAIS DEPTOS ELES TRABALHAM?)
  SELECT D.NM_DEPTO,
         D.SG_DEPTO,
         F.NM_FUNCIONARIO,
         F.VL_SAL_MEN,
         F.DT_ADMISSAO
    FROM T_SIP_DEPARTAMENTO D INNER JOIN T_SIP_FUNCIONARIO F
      ON(D.CD_DEPTO = F.CD_DEPTO) --PK = FK -> JUNÇÃO INTERN POR IGUALDADE
   WHERE F.DT_ADMISSAO >= TO_DATE('01/08/2015' , 'DD/MM/YYYY')
ORDER BY D.NM_DEPTO, F.NM_FUNCIONARIO;

-- JUNÇÃO INTERNA (INNER JOIN) DE DUAS OU MAIS TABELAS
-- RECUPERAR TODOS OS PROJETOS QUE TENHAM SUAS IMPLANTAÇÕES INICIADAS
-- POR FUNCIONARIOS
-- QUAIS SÃO OS PROJETOS EM IMPLANTAÇÃO E QUAIS FUNCIONARIOS TRABALHAM NESSES PROJETOS?
-- EXEMPLO COM INNER JOIN - PADRÃO SQL/99

    SELECT P.NM_PROJETO,
           F.NM_FUNCIONARIO,
           I.DT_ENTRADA, I.DT_SAIDA
      FROM T_SIP_PROJETO P INNER JOIN T_SIP_IMPLANTACAO I
        ON (P.CD_PROJETO = I.CD_PROJETO) --PK=FK
INNER JOIN T_SIP_FUNCIONARIO F
        ON (F.NR_MATRICULA = I.NR_MATRICULA);
