-- FUNÇÕES DE GRUPO E AGRUPAMENTOS
-- ENVOLVEM A RECUPERAÇÃO DE UM CONJUNTO (GRRUPO) DE LINHAS
-- OU ATE A TABELA INTEIRA, COM OBJETIVO DE DAR ALGUM TIPO DE RESULTADO

-- FUNÇÕES DE GRUPO - ATUANDO A PARTIR DE TODAS AS LINHAS DA TABELA
-- EXEMPLO: CONTAGEM, SOMATORIA, MEDIA, VALOR MAXIMO, VALOR MINIMO, DESVIO PADRAO, VARIANCIA

-- COUNT() - CONTAGEM
-- RECUPERAR A QTDE DE DEPARTAMENTOS
SELECT COUNT(*) "QUANTIDADE DE DEPTOS" FROM T_SIP_DEPARTAMENTO;
-- CONTAGEM BASEADA EM TODAS AS COLUNAS DA TABELA

-- COUNT() - APONTANDO PARA UMA COLUNA ESPECIFICA
-- RECUPERANDO A QTDE DE PROJETOS FINALIZADOS
SELECT COUNT(DT_FIM_PROJETO) "PROJETOS FINALIZADOS" FROM T_SIP_PROJETO;
-- CONTAGEM BASEADA APENAS NA COLUNA INFORMADA

-- COUNT() - COM CONDIÇÃO NA CLAUSULA WHERE
-- RECUPERANDO A QTDE DE PROJETOS NAO FINALIZADOS
SELECT COUNT(CD_PROJETO) "PROJETOS NÃO FINALIZADOS" FROM T_SIP_PROJETO WHERE DT_FIM_PROJETO IS NULL;
  -- CONTAGEM A PARTIR DE UMA COLUNA ESPECIFICA (PK)

 -- VALIDANDO PROJETOS NAO FINALIZADOS

-- COUNT() E DISTINCT
--  QTDE TOTAL DE IMPLANTACOES
SELECT COUNT(CD_PROJETO) "QUANTIDADE DE IMPLANTAÇÕES" FROM T_SIP_IMPLANTACAO;
  
-- RECUPERAR A QTDE DE PROJETOS EM IMPLANTACAO
SELECT COUNT(DISTINCT CD_PROJETO) "PROJETOS EM IMPLANTAÇÃO" FROM T_SIP_IMPLANTACAO;

-- RECUPERAR A QTDE IMPLANTACÕES QUE FORAM FINALIZADAS
-- IMPLANTACOES FINALIZADAS

-- IMPLANTACAO FINALIZADA POSSUI DATA DA SAIDA PREENCHIDA
SELECT COUNT(DT_SAIDA) FROM T_SIP_IMPLANTACAO;

 
-- QUANTOS PROJETOS POSSUEM IMPLANTACOES FINALIZADAS
 SELECT COUNT(DISTINCT CD_PROJETO) FROM T_SIP_IMPLANTACAO WHERE dt_saida IS NOT NULL;
 -- SUM() - SOMATORIA
-- RECUPERAR A SOMATORIA DE SALARIOS (DE TODA EMPRESA)
SELECT SUM(VL_SAL_MEN) "SALARIO TOTAL" FROM T_SIP_FUNCIONARIO;  
-- AVG() - MEDIA
-- RECUPERAR A MEDIA DOS SALARIOS DE TODA EMPRESA
SELECT ROUND(AVG(VL_SAL_MEN),2)"MEDIA SALARIAL" FROM T_SIP_FUNCIONARIO;
-- ASSOCIANDO...SEM USAR AVG() -- SOMATORIA/QTDE
SELECT ROUND(SUM(VL_SAL_MEN)/ COUNT(NR_MATRICULA),2)"MEDIA SALARIAL" FROM T_SIP_FUNCIONARIO;
-- MIN() - MENOR VALOR
-- RECUPERAR O MENOR SALARIO DE TODA EMPRESA
SELECT MIN(VL_SAL_MEN) "MENOR SALARIO" FROM T_SIP_FUNCIONARIO;
-- MAX() - MAIOR VALOR  
-- RECUPERAR O MAIOR SALARIO DE TODA EMPRESA
SELECT MAX(VL_SAL_MEN) "MAIOR SALARIO" FROM T_SIP_FUNCIONARIO;
-- AGRUPAMENTOS
-- CRIANDO GRUPOS DE DADOS
-- RECUPERAR A QTDE DE DEPENDENTES DE CADA FUNCIONARIO

SELECT NR_MATRICULA,COUNT (CD_DEPENDENTE) "QUANTIADE DE DEPENDENTE" FROM T_SIP_DEPENDENTE GROUP BY NR_MATRICULA;

-- SO E POSSIVEL VISUALIZAR O QUE FIZER PARTE DO GRUPO
-- ALEM DOS DADOS QUE FIZEREM PARTE DO GRUPO, SÓ E POSSIVEL
-- EXIBIR O RESULTADO DE UMA FUNÇÃO DE GRUPO (COUNT,SUM, AVG, MIN, MAX...)

-- CRIANDO GRUPOS DE DADOS
-- RECUPERAR A MEDIA SALARIAL POR DEPTO
-- AGRUPAR POR DEPTO E APLICAR A MEDIA POR DEPTO
SELECT CD_DEPTO, ROUND(AVG(VL_SAL_MEN),2) "MEDIA SALARIAL" FROM T_SIP_FUNCIONARIO GROUP BY CD_DEPTO;

--INSERINDO FILTRO DE TABELA COM WHERE
-- AGRUPAR APENAS OS DEPTOS DE CODIGO 1, 4 E 5
-- FAREMOS UM FILTRO ANTES DE AGRUPAR
    SELECT CD_DEPTO,COUNT(NR_MATRICULA) "QUANTIDADE FUNCIONARIOS",
    SUM(VL_SAL_MEN) "TOTAL DE SALARIO",
    ROUND(AVG(VL_SAL_MEN),2)"MEDIA SALARIAL" 
      FROM T_SIP_FUNCIONARIO   
     WHERE CD_DEPTO IN(1,4,5) 
  GROUP BY CD_DEPTO 
  ORDER BY "MEDIA SALARIAL";

-- INSERINDO FILTRO DE GRUPO COM HAVING
-- DEPOIS QUE OS GRUPOS FOREM MONTADOS IREMOS RECUPERAR APENAS OS
-- GRUPOS QUE TIVEREM TOTAL DE SALARIO SUPERIOR A 10000,00

   SELECT CD_DEPTO,COUNT(NR_MATRICULA) "QUANTIDADE FUNCIONARIOS",
      SUM(VL_SAL_MEN) "TOTAL DE SALARIO",
    ROUND(AVG(VL_SAL_MEN),2)"MEDIA SALARIAL" 
      FROM T_SIP_FUNCIONARIO   
     WHERE CD_DEPTO IN(1,4,5) 
  GROUP BY CD_DEPTO 
    HAVING SUM (VL_SAL_MEN)> 10000
  ORDER BY "MEDIA SALARIAL";    
  
-- CRIANDO GRUPOS E JUNTANDO TABELAS
-- RECUPERAR A MEDIA SALARIAL POR DEPTO, EXIBINDO O NOME DO DEPTO  
SELECT F.CD_DEPTO, ROUND(AVG(F.VL_SAL_MEN),2) "MEDIA SALARIAL", D.NM_DEPTO
FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPARTAMENTO D 
ON (D.CD_DEPTO = F.CD_DEPTO)
GROUP BY F.CD_DEPTO, D.NM_DEPTO;

--INSERINDO WHERE E HAVING

   SELECT F.CD_DEPTO,D.NM_DEPTO,
    COUNT(F.NR_MATRICULA) "QUANTIDADE FUNCIONARIOS",
      SUM(F.VL_SAL_MEN) "TOTAL DE SALARIO",
    ROUND(AVG(F.VL_SAL_MEN),2)"MEDIA SALARIAL" 
      FROM T_SIP_FUNCIONARIO F INNER JOIN T_SIP_DEPARTAMENTO D  
        ON (D.CD_DEPTO = F.CD_DEPTO)
     WHERE F.CD_DEPTO IN(1,4,5) 
  GROUP BY F.CD_DEPTO, D.NM_DEPTO
    HAVING SUM (VL_SAL_MEN)> 10000
  ORDER BY "MEDIA SALARIAL";  