-- COMENTARIO DE LINHA
/*
COMENTARIO DE BLOCO

 LINGUAGEM SQL - LINGUAGEM ESTRUTURADA PARA CONSULTA
DDL = DIVISÃO RESPONSAVEL PELA DEFINIÇÃO DA ESTRUTURA
LIGUAGEM DE DEFINIÇÃO DE DADOS DE DADOS
CREATE TABLE
ALTER TABLE
DROP TABLE

BOA PRATICA
1) CRIAR TABELAS COM CAMPOS/TIPO DADO/TAMANHO
2) COM COMANDO DE ALTERAÇÃO:
    ADICIONAR CHAVE PRIMARIA
    ADICIONAR CHECK 
    ADICIONAR UNIQUE
AO TERMINO DA CRIAÇÃO DAS TABELAS E CONTRANTS ACIMA
NO FINAL DO ARQUIVO
3) COM COMANDOS DE ALTERAÇÃO
    ADICIONAR AS CHAVES ESTRANGEIRAS
ADICIONALMENTE DEIXAMOS NO INICIO DO ARQUIVO OS COMANDOS DE DELEÇÃO...
... PARA USO QUANDO NECESSARIO

-- DELEÇÃO DAS TABELAS

--DROP TABLE T_SIP_DEPARTAMENTO; --DROP TABLE + <NOME TABELA>
--DROP TABLE T_SIP_FUNCIONARIO;
--DROP TABLE T_SIP_DEPENDENTE;
--DROP TALBE T_SIP_PROJETO
--DROP TABLE T_SIP_IMPLANTACAO;

--DELEÇÃO EM CASCATA

DROP TABLE T_SIP_IMPLANTACAO       CASCADE CONSTRAINTS;
DROP TABLE T_SIP_DEPENDENTE        CASCADE CONSTRAINTS;
DROP TABLE T_SIP_FUNCIONARIO        CASCADE CONSTRAINTS;
DROP TABLE T_SIP_DEPARTAMENTO   CASCADE CONSTRAINTS;
DROP TABLE T_SIP_PROJETO               CASCADE CONSTRAINTS;
*/

--CASCADE CONSTRAINTS --> ELIMINA A TABELA E ELIMINA EM CASCATA OS RELACIONAMENTOS

/*CREATE TABLE T_SIP_DEPARTAMENTO(
    CD_DEPTO        NUMBER(3)              NOT NULL,
    NM_DEPTO       VARCHAR2 (30)       NOT NULL,
    SG_DEPTO        CHAR(3)                    NOT NULL
);

--DESCRIBE T_SIP_DEPARTAMENTO MOSTRA NO OUTPUT A TABELA
-- ADICIONAR A CONSTRANT CHAVE PRIMARIA

        ALTER TABLE T_SIP_DEPARTAMENTO --ALTER TABLE<NOME_TABLE>
ADD CONSTRAINT PK_SIP_DEPARTAMENTO --ADICIONAR CONSTRAINT/ NOME DA CONSTRAINT
        PRIMARY KEY (CD_DEPTO); --TIPO CONSTRAINT (PK) / CAMPO PK
        
--ADICIONAR A CONSTRAINT UNIQUE
        ALTER TABLE T_SIP_DEPARTAMENTO --ALTER TABLE<NOME_TABLE>
ADD CONSTRAINT UN_SIP_DEPTO_NOME--ADICIONAR CONSTRAINT/ NOME DA CONSTRAINT
                    UNIQUE (NM_DEPTO);--TIPO CONSTRAINT UNIQUE / CAMPO QUE NÃO SE REPETE
*/

--CRIAR TABELA FUNCIONARIO
/*CREATE TABLE T_SIP_FUNCIONARIO(
    NR_MATRICULA           NUMBER(5)            NOT NULL,
    CD_DEPTO                      NUMBER(3)           NOT NULL,
    NM_FUNCIONARIO      VARCHAR2(50)     NOT NULL,
    DT_NASCIMENTO        DATE                       NOT NULL,
    DT_ADMISSAO              DATE                       NOT NULL,
    DS_ENDERECO             VARCHAR2(100)   NOT NULL,
    VL_SAL_MEN                NUMBER(7,2)         NOT NULL
);
ALTER TABLE        T_SIP_FUNCIONARIO
ADD CONSTRAINT     PK_SIP_FUNCIONARIO
PRIMARY KEY       (NR_MATRICULA);
    

ALTER TABLE T_SIP_FUNCIONARIO
ADD CONSTRAINT FK_SIP_FUNC_DEPTO
    FOREIGN KEY (CD_DEPTO);

ALTER TABLE T_SIP_FUNCIONARIO
ADD CONSTRAINT CK_SIP_FUNC_SALARIO
    CHECK (VL_SAL_MEN >= 1212);
 */
    
--describe T_SIP_FUNCIONARIO
/*CREATE TABLE T_SIP_DEPENDENTE(
    NR_MATRICULA        NUMBER(5)       NOT NULL,
    CD_DEPENDENTE       NUMBER(2)       NOT NULL,
    NM_DEPENDENTE       VARCHAR2(50)    NOT NULL,
    DT_NASCIMENTO       DATE            NOT NULL
);
--PRIMARY KEY
ALTER TABLE     T_SIP_DEPENDENTE
ADD CONSTRAINT  PK_SIP_DEPENDENTE
PRIMARY KEY     (NR_MATRICULA, CD_DEPENDENTE);  
DESCRIBE T_SIP_DEPENDENTE
*/

/*CREATE TABLE T_SIP_PROJETO(
    CD_PROJETO          NUMBER(5)       NOT NULL,
    NM_PROJETO          VARCHAR2(40)    NOT NULL,
    DT_INICIO_PROJETO   DATE            NOT NULL,
    DT_FIM_PROJETO  DATE            NULL
);

--PRIMARY KEY
ALTER TABLE      T_SIP_PROJETO
ADD CONSTRAINT   PK_SIP_PROJETO
PRIMARY KEY     (CD_PROJETO);

--CHECK
ALTER TABLE     T_SIP_PROJETO
ADD CONSTRAINT  CK_SIP_PROJETO_DATA
CHECK          (DT_FIM_PROJETO > DT_INICIO_PROJETO);

--UNIQUE
ALTER TABLE      T_SIP_PROJETO
ADD CONSTRAINT   UN_SIP_PROJETO_NOME
UNIQUE          (NM_PROJETO);
*/

/*CREATE TABLE T_SIP_IMPLANTACAO(
    CD_PROJETO          NUMBER(5)       NOT NULL,
    CD_IMPLANTACAO  NUMBER(3)       NOT NULL,
    NR_MATRICULA       NUMBER(5)       NOT NULL,
    DT_ENTRADA          DATE                  NOT NULL,
    DT_SAIDA                DATE                  NULL
);

--PRIMARY KEY 
ALTER TABLE         T_SIP_IMPLANTACAO
ADD CONSTRAINT PK_SIP_IMPLANTACAO
PRIMARY KEY       (CD_IMPLANTACAO,CD_PROJETO);

--CHECK
ALTER TABLE         T_SIP_IMPLANTACAO
ADD CONSTRAINT CK_SIP_IMPLANTACAO_DATA
CHECK                  (DT_SAIDA > DT_ENTRADA);
*/

----------------------------------------------------------------------------
-- ADICIONAR AS CHAVE ESTRANGEIRAS - SEMPRE NO FINAL DO ARQUIVO
-- ASSIM TEMOS TODAS AS TABLEAS E CHAVES PRIMARIAS CRIADAS
-----------------------------------------------------------------------------
--RELACIONAMENTO ENTRE FUNCIONARIO (DESTINO) E DEPARTAMENTO (ORIGEM)

--FOREIGN KEY FUNCIONARIO
/*ALTER TABLE         T_SIP_FUNCIONARIO
ADD CONSTRAINT  FK_SIP_FUNC_DEPTO
FOREIGN KEY       (CD_DEPTO) --TIPO CONSTRAINT = FK / NOME DO CAMPO CHAVE ESTRANGEIRA
REFERENCES         T_SIP_DEPARTAMENTO (CD_DEPTO);
-- REFERENCES = RELACIONAMENTO/ NOME DA TABELA REFERENCIADA
--NOME DO CAMPO CHAVE PRIMARIA NA TABELA REFERENCIADA (TAB_ORIGEM)

--FOREING KEY DEPENDENTE
ALTER TABLE T_SIP_DEPENDENTE
ADD CONSTRAINT FK_SIP_DEPENDENTE_FUNC
FOREIGN KEY (NR_MATRICULA)
REFERENCES  T_SIP_FUNCIONARIO (NR_MATRICULA);

--FOREING KEY IMPLANTACAO(NR_MATRICULA)
ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT FK_SIP_IMPLANT_FUNC
FOREIGN KEY (NR_MATRICULA)
REFERENCES T_SIP_FUNCIONARIO(NR_MATRICULA);

--FOREING KEY IMPLANTACAO(CD_PROJETO)
ALTER TABLE T_SIP_IMPLANTACAO
ADD CONSTRAINT FK_SIP_IMPLANT_PROJETO
FOREIGN KEY (CD_PROJETO)
REFERENCES T_SIP_PROJETO(CD_PROJETO);
*/